### PR TITLE
Make Pather compatible to CommonJS, AMD and global L

### PR DESCRIPTION
**Pull request by kuuup**
This has to be tested in your environment with global L.
Maybe someone could run a test with AMD.

### CODE REVIEW

**Comment by Wildhoney** [comment]
Why do we have `if (false &&...`?

**Comment by kuuup** [comment]
Tried to setup an AMD environment, but gave up, sorry

**Comment by Wildhoney** [comment]
Ah, no problem :+1: Thanks for adding this.

All good to merge now?

**Comment by kuuup** [comment]
Should be.
But I have to repeat: I did NOT test it with global L or AMD.

**Comment by kuuup** [comment]
After more tests I found multiple issues. I'll close this one for now because I need more time to fix everything.

**Comment by Wildhoney** [comment]
:+1: Tests worked for the global version, but unsure about the AMD version.

**Pull request closed without merging**
